// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendSys.Infrastructure.Data;

#nullable disable

namespace VendSys.Infrastructure.Migrations
{
    [DbContext(typeof(VenDexDbContext))]
    [Migration("20260422210821_AddStoredProcedures")]
    partial class AddStoredProcedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VendSys.Domain.DexLaneMeter", b =>
                {
                    b.Property<int>("DexLaneMeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DexLaneMeterId"));

                    b.Property<int>("DexMeterId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVends")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValueOfPaidSales")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DexLaneMeterId");

                    b.HasIndex("DexMeterId");

                    b.ToTable("DEXLaneMeter", "dbo");
                });

            modelBuilder.Entity("VendSys.Domain.DexMeter", b =>
                {
                    b.Property<int>("DexMeterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DexMeterId"));

                    b.Property<DateTime>("DEXDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MachineSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValueOfPaidVends")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("DexMeterId");

                    b.HasIndex("Machine", "DEXDateTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_DEXMeter_Machine_DEXDateTime");

                    b.ToTable("DEXMeter", "dbo");
                });

            modelBuilder.Entity("VendSys.Domain.DexLaneMeter", b =>
                {
                    b.HasOne("VendSys.Domain.DexMeter", null)
                        .WithMany()
                        .HasForeignKey("DexMeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DEXLaneMeter_DEXMeter");
                });
#pragma warning restore 612, 618
        }
    }
}
